# Generated by Django 2.0.2 on 2018-02-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_auto_20180227_0516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUsers',
            new_name='User',
        ),
    ]
