# Generated by Django 2.0.2 on 2018-02-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='SiteUsers',
        ),
    ]
